baseurl = "/"
copyright = ""
defaultContentLanguage = "en-us"
destination = "public"
enableEmoji = true
enableRobotsTXT = false
languageCode = "en-us"
metaDataFormat = "yaml"
paginate = 10
pluralizeListTitles = false
relativeURLs = false
disablePathToLower = true
uglyURLs = false
smartDashes = true
title = ""
canonifyURLs = true
enableGitInfo = true
ignoreFiles = "content/how-to/retired-articles/"
[permalinks]
    how-to = "/how-to/:filename"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.asciidocExt]
    backend = "html5"
    docType = "article"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = true
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[[menu.footer]]
    name = "Support Network Home"
    parent = "Support Network"
    url = "/support"
    weight = 1
[[menu.footer]]
    name = "Rackspace How-To"
    parent = "Support Network"
    url = "/support/how-to"
    weight = 2
[[menu.footer]]
    name = "API Documentation"
    parent = "Support Network"
    url = "https://docs.rackspace.com/docs/"
    weight = 3
[[menu.footer]]
    name = "Developer Center"
    parent = "Support Network"
    url = "https://docs.rackspace.com/"
    weight = 4
[[menu.footer]]
    name = "About"
    parent = "About Rackspace"
    url = "https://www.rackspace.com/about"
    weight = 5
[[menu.footer]]
    name = "Customer Stories"
    parent = "About Rackspace"
    url = "https://www.rackspace.com/customer-stories"
    weight = 6
[[menu.footer]]
    name = "Events"
    parent = "About Rackspace"
    url = "https://www.rackspace.com/events"
    weight = 7
[[menu.footer]]
    name = "Programs"
    parent = "About Rackspace"
    url = "https://www.rackspace.com/responsibility"
    weight = 8
[[menu.footer]]
    name = "News"
    parent = "NA"
    identifier = "N/A"
    url = "https://www.rackspace.com/newsroom"
    weight = 9
[[menu.footer]]
    name = "Contact Information"
    parent = "NA"
    url = "https://www.rackspace.com/contact"
    weight = 10
[[menu.footer]]
    name = "Legal"
    parent = "NA"
    url = "https://www.rackspace.com/information/legal"
    weight = 11
[[menu.footer]]
    name = "Careers"
    parent = "NA"
    url = "https://www.jobvite.com/support/job-seeker-support"
    weight = 12
[[menu.footer]]
    name = "The Rackspace Blog"
    parent = "Blogs"
    url = "https://www.rackspace.com/blog"
    weight = 13
[[menu.footer]]
    name = "Expert Insights Tech Blog"
    parent = "Blogs"
    url = "https://docs.rackspace.com/blog/"
    weight = 14
[[menu.footer]]
    name = "Solve: Thought Leadership"
    parent = "Blogs"
    url = "https://www.rackspace.com/solve"
    weight = 15
[[menu.footer]]
    name = "Privacy Statement"
    parent = "Site Information"
    url = "https://www.rackspace.com/information/legal/privacystatement"
    weight = 16
[[menu.footer]]
    name = "Website Terms"
    parent = "Site Information"
    url = "https://www.rackspace.com/information/legal/websiteterms"
    weight = 17
[[menu.footer]]
    name = "Trademarks"
    parent = "Site Information"
    url = "https://www.rackspace.com/information/legal/copyrights_trademarks/"
    weight = 12
[[menu.footer]]
    name = "Style Guide for Technical Content"
    parent = "Site Information"
    url = "https://docs.rackspace.com/docs/style-guide/"
    weight = 12

[[menu.main]]
    identifier = "support_home"
    name = "Support Home"
    url = "/support"
    weight = 1
[[menu.main]]
    identifier = "how_to"
    name = "How-To"
    url = "/support/how-to"
    weight = 2
[[menu.main]]
    identifier = "developer_documentation"
    name = "Developer Documentation"
    url = "https://docs.rackspace.com/docs/"
    weight = 3
[[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "#"
    post = ""
    weight = 4
    [[menu.main]]
        identifier = "technical-blog"
        name ="Expert Insights Tech Blog"
        url ="https://docs.rackspace.com/blog/"
        weight = 1
        parent = "blogs"
    [[menu.main]]
        identifier = "rackspace-blog"
        name = "Rackspace Blog"
        url = "https://www.rackspace.com/blog"
        weight = 2
        parent = "blogs"
    [[menu.main]]
        identifier = "solve"
        name = "Solve: Thought Leadership"
        url = "https://www.rackspace.com/solve"
        weight = 3
        parent = "blogs"
[[menu.buttons]]
    identifier = "buynow"
    name = "Buy Now"
    url = "#"
    weight = 5
[[menu.buttons]]
    identifier = "login"
    name = "Login"
    url = "#"
    weight = 6


[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
dateformat = "January 2, 2006"
description = ""
ghrepo = "https://github.com/rackerlabs/support-how-to"
ghrepo_edit = "https://github.com/rackerlabs/support-how-to/edit/master/hugo/content/"
ghrepo_new = "https://github.com/rackerlabs/support-how-to/issues/new"
images = ["/img"]

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink", "description", "created_by", "created_date", "last_modified_by", "last_modified_date"]
  params = ["categories", "tags", "description"]

[related]
includeNewer = true
threshold = 10
toLower = true
[[related.indices]]
name = "Description"
weight = 250
[[related.indices]]
name = "Type"
weight = 200
[[related.indices]]
name = "Product_url"
weight = 150
[[related.indices]]
name = "Product"
weight = 150
[[related.indices]]
name = "Created_by"
weight = 150
[[related.indices]]
name = "Category"
weight = 150
[[related.indices]]
name = "Title"
weight = 100
[[related.indices]]
name = "Created_date"
pattern = "2006"
weight = 100
[[related.indices]]
name = "Audit_date"
pattern = "2006"
weight = 100
[taxonomies]
created_by = "created_by"
category = "category"
type = "type"
product = "product"
description = "description"
