#!/bin/bash
#
# Used by Travis to submit named assets to the correct environments.

set -euo pipefail

PUBLISH="false"

if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
  case ${TRAVIS_BRANCH} in
    master)
      echo "Submitting to production."
      PUBLISH="true"
      ;;
    *)
      echo "Not submitting ${TRAVIS_BRANCH} anywhere."
      ;;
  esac
else
  echo "Not submitting pull request build anywhere."
fi

if [ "${PUBLISH}" = "true" ]; then
  kc-preparer
fi
